version: "3"
services:
  web:
    image: nginx:1.25-alpine
    volumes:
      - ./etc/conf.d/:/etc/nginx/conf.d/
      - ./etc/stream.d/:/etc/nginx/stream.d/
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/mime.types:/etc/nginx/mime.types
    container_name: web
    extra_hosts:
      - "web-ui-service:192.168.3.201"
      - "download-box-service:192.168.3.202"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
