version: "3"
services:
  minio:
    image: quay.io/minio/minio
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ 'server', '/data','--console-address' ,':9001','--address', '0.0.0.0:9000' ]
    container_name: minio
    environment:
      - "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
