version: "3"
services:
  postgresql-server:
    image: postgis/postgis:17-alpine
    # image: postgis/postgis:16-3.4-alpine
    hostname: "postgresql"
    container_name: "postgresql"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=example"
    # 容器内数据目录 /var/lib/postgresql/data
    # auth_user: postgres
    # auth_password: example
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
