version: "3"
services:
  rabbitmq-server:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: my-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

# client library
# https://www.rabbitmq.com/client-libraries/devtools
# https://hub.docker.com/_/rabbitmq
