version: "3"
services:
  redis-server:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    container_name: redis-server
    volumes:
      - ./redist-data:/data
    networks:
      - default

# redis 配置文件 redis.conf
# https://download.redis.io/redis-stable/redis.conf
