version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: "es01"
    hostname: "es01"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - http.port=9200
      - node.name=es01
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://0.0.0.0:1358"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "cat /etc/hosts"]
      interval: 1s
      timeout: 5s
      retries: 120
    sysctls:
      net.core.somaxconn: 1024
    #  net.ipv4.tw_reuse: 1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_RAW
      - NET_ADMIN

# Runtime privilege and Linux capabilities
# https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
  neo4j-service:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
   #  # 容器内数据目录  # /data
