name: build-swoole-cli

on: [push, pull_request]

jobs:
  linux:
    if: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        git submodule update --init
    - name: Prepare-1
      uses: addnab/docker-run-action@v3
      with:
        image: docker.io/jingjingxyk/build-swoole-cli:download-box-nginx-alpine-20230329T114730Z
        options: -v ${{ github.workspace }}:/work -w /work
        run: |
          mkdir -p /work/pool/lib
          mkdir -p /work/pool/ext
          cp -rf /usr/share/nginx/html/extensions/* /work/pool/ext
          cp -rf /usr/share/nginx/html/libraries/*  /work/pool/lib
    - name: Prepare-2
      uses: addnab/docker-run-action@v3
      with:
        image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-20230330T153237Z
        options: -v ${{ github.workspace }}:/work -w /work
        run: |
          composer update 
          php prepare.php  +inotify  +ds +apcu
          chmod a+x ./make.sh
    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-20230330T153237Z
        options: -v ${{ github.workspace }}:/work -w /work
        run: |
          ./make.sh config
          ./make.sh build
          ./bin/swoole-cli -v
  cygwin:
    if: 0
    runs-on: windows-latest
    steps:
    - name: Prepare git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
    - name: Cache cygwin packages
      id: cache-cygwin
      uses: actions/cache@v3
      env:
        cache-name: cache-cygwin-packages
      with:
        path: C:/cygwin-packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install deps
      uses: cygwin/cygwin-install-action@v2
      with:
        platform: x64
        packages: wget tar libtool re2c bison gcc-g++ autoconf automake openssl libpcre2-devel libssl-devel libcurl-devel libxml2-devel libxslt-devel libgmp-devel ImageMagick libpng-devel libjpeg-devel libfreetype-devel libwebp-devel libsqlite3-devel zlib-devel libbz2-devel libzip-devel libicu-devel libonig-devel libcares-devel libsodium-devel libyaml-devel libMagick-devel
    - name: Install re2c
      run: |
        bash ./sapi/install-re2c.sh
    - name: Configure
      run: |
        uname -a
        git submodule update --init
        bash ./sapi/cygwin-config.sh
    - name: Build
      run: |
        make -j $(nproc)
        ./bin/swoole-cli -v
