name: build-swoole-cli-linux-x86_64

on: [ push, pull_request ]

jobs:
  linux-x86_64:
    if: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Source Code
        run: |
          lscpu
          echo $PATH
          env
          docker info
          id -u
          id -g
          who
          cat /etc/os-release
          hostnamectl
          uname -s
          uname -m
          uname -r
          export IPV6=$(ip -6 address show  | grep inet6 | awk '{print $2}' | cut -d'/' -f1 | sed -n '2p')
          export IPV4=$(ip -4 address show  | grep inet | grep -v 127.0.0 | awk '{print $2}' | cut -d'/' -f1 | sed -n '1p')
          echo $IPV4
          echo $IPV6
          echo "X_IPV6=${IPV6}" >> $GITHUB_ENV
          echo "X_IPV4=${IPV4}" >> $GITHUB_ENV

          git submodule update --init

      - name: Prepare Libraries and Extensions
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:download-box-nginx-alpine-20230505T112517Z
          # image: phpswoole/swoole-cli-builder:download-box-nginx-alpine-20230505T112517Z
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            set -eux
            mkdir -p pool/lib
            mkdir -p pool/ext
            mkdir -p ext
            cp -rf /usr/share/nginx/html/extensions/* pool/ext
            cp -rf /usr/share/nginx/html/libraries/* pool/lib
      - name: Prepare
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-swoole-cli-x86_64-20230505T120137Z
          # image: phpswoole/swoole-cli-builder:all-dependencies-alpine-swoole-cli-x86_64-20230505T120137Z
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            set -eux
            # export PATH=/work/bin/runtime:$PATH  # 容器已经内置 php 和 composer 容器

            # composer update --no-dev  --optimize-autoloader
            composer update   --optimize-autoloader
            php prepare.php  --with-global-prefix=/usr --with-swoole-pgsql=1 +inotify +apcu +ds +xlswriter +ssh2 +pgsql +pdo_pgsql

            chmod a+x make.sh
            head -n 20 make.sh
            php ./vendor/bin/phpunit ./sapi/unit/MainTest.php  --list-tests
            php ./vendor/bin/phpunit ./sapi/unit/MainTest.php

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-swoole-cli-x86_64-20230505T120137Z
          # image: phpswoole/swoole-cli-builder:all-dependencies-alpine-swoole-cli-x86_64-20230505T120137Z
          options: -v ${{ github.workspace }}:/work -w /work
          run: |

            apk update
            apk add libc++-static

            bash ./make.sh liblz4
            bash ./make.sh liblzma
            bash ./make.sh libzstd
            bash ./make.sh libzip
            bash ./make.sh brotli
            bash ./make.sh curl
            bash ./make.sh pgsql
            bash ./make.sh libraw
            bash ./make.sh libtiff
            bash ./make.sh lcms2
            bash ./make.sh imagemagick

            apk add ninja python3 py3-pip  nasm
            pip3 install meson

            bash ./make.sh dav1d
            bash ./make.sh aom
            bash ./make.sh libgav1
            bash ./make.sh svt_av1
            bash ./make.sh libyuv

            bash ./make.sh config
            bash ./make.sh build
            bash ./make.sh archive
            # ./bin/swoole-cli ./vendor/bin/phpunit ./sapi/unit/MainTest.php  --list-tests
            # ./bin/swoole-cli ./vendor/bin/phpunit ./sapi/unit/MainTest.php

      - name: Show Build Result
        run: |
          ./bin/swoole-cli -v
          ./bin/swoole-cli -m
          ./bin/swoole-cli --ri swoole
          file ./bin/swoole-cli
          readelf -h ./bin/swoole-cli
          ./bin/swoole-cli -r "echo PHP_VERSION;"

      - name: production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: swoole-cli
          retention-days: 7
          path: ./bin/swoole-cli
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: swoole-cli-*-linux-x64.tar.xz
