name: linux-download-ci

on:
  push:
  pull_request:

jobs:
  download-webrtc:
    runs-on: ubuntu-latest
    if: 0
    steps:
      - uses: actions/checkout@v4
      - name: prepare Environment
        run: |
          git config --global core.autocrlf false
          # 不再关心文件的权限
          git config --global core.filemode false
          # 让 Git 显示颜色，会让命令输出看起来更醒目
          git config --global color.ui true
          sudo apt install -y curl wget bash

      - name: Prepare depot_tools
        run: |
          # https://webrtc.googlesource.com/src/+/main/docs/native-code/development/prerequisite-sw/
          # https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up

          git clone --progress -b main https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=${{ github.workspace }}/depot_tools:$PATH
          echo "PATH=$PATH:${{ github.workspace }}/depot_tools" >> $GITHUB_ENV

      - name: Maximize build space
        if: 1
        shell: bash
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          df -h

      - name: Download Webrtc
        run: |
          # https://webrtc.googlesource.com/src/+/main/docs/native-code/development
          fetch webrtc
          cd src && ./build/install-build-deps.sh
          gclient sync
