name: sync to gitee

on:
  push:
jobs:
  sync-to-gitee:
    if: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: |
          git remote -v
          git remote add git@gitee.com:jingjingxyk/swoole-cli.git
          git remote -v
          # git push gitee --all
          # git push gitee <branch name> --force
