name: build-php-cli-windows

on:
  push:
  pull_request:

env:
  BUILD_PHP_VERSION: 8.2.13

jobs:
  windows-native:
    if: 0
    runs-on: windows-2022
    strategy:
      matrix:
        php-version:
          - "8.3.3"
    steps:
      - uses: actions/checkout@v4
      - name: show environment info
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            curl
      - uses: actions/setup-dotnet@v1
      - uses: ilammy/msvc-dev-cmd@v1.9.0
        with:
          arch: amd64

      - name: test
        shell: cmd
        run: |
          set
          git clone -b master --depth=1 https://github.com/php/php-sdk-binary-tools.git
          git clone -b php-8.3.7 --depth=1 https://github.com/php/php-src.git

          echo %~dp0
          echo %cd%
          SET  CURRENT_DIR=%~dp0

          php-sdk-binary-tools\phpsdk-vs17-x64.bat -cur_console:d:%CURRENT_DIR%\php-src
          set

