name: build-php-cli-windows

on:
  push:
  pull_request:

env:
  BUILD_PHP_VERSION: 8.2.13

jobs:
  windows-native:
    if: 1
    runs-on: windows-2022
    strategy:
      matrix:
        php-version:
          - "8.3.3"
    steps:
      - uses: actions/checkout@v4
      - name: show environment info
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all
          set
          git clone -b master --depth=1 https://github.com/php/php-sdk-binary-tools.git
          echo %~dp0
          echo %cd%
          SET  CURRENT_DIR=%~dp0
          cd php-sdk-binary-tools

          phpsdk-vs17-x64.bat
          set

