name: build-php-cli-windows-2019

on:
  push:
  pull_request:

env:
  BUILD_PHP_VERSION: 8.2.13

jobs:
  windows-native:
    if: 1
    runs-on: windows-2019
    strategy:
      matrix:
        php-version:
        #  - "8.2.13"
        #  - "8.1.27"
          - "8.3.7"

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: amd64
      - name: show environment info
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all
          echo "BUILD_PHP_VERSION=${{ matrix.php-version }}" >> $Env:GITHUB_ENV

      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            curl git zip unzip tar xz

      - name: prepare build environment and download source code
        shell: msys2 {0}
        run: |
          CURRENT_DIR=$(pwd)
          echo $CURRENT_DIR

          # msys2 下载安装  git curl wget openssl zip unzip xz  lzip 软件包
          bash sapi/quickstart/windows/native-build/msys2/msys2-install-soft.sh

          # 准备 PHP 运行时 并执行 composer install
          bash sapi/quickstart/windows/native-build/msys2/msys2-download-php-runtime.sh

          # 提前准备下载依赖库
          bash sapi/download-box/download-box-get-archive-from-server.sh

          # 准备 依赖库 和 扩展
          bash sapi/quickstart/windows/native-build/msys2/msys2-download-source-code.sh

          # 准备 PHP 源码 和 PHP SDK
          bash sapi/quickstart/windows/native-build/msys2/msys2-download-php-and-php-sdk.sh

          # 构建库准备环境依赖
          bash sapi/quickstart/windows/native-build/msys2/msys2-download-deps-soft.sh

      - name: Install Soft And  Set  Github ENV variables
        shell: cmd
        run: |
          sapi\quickstart\windows\native-build\install-deps-soft.bat


#
#      - name: show PHPSDK env
#        shell: cmd
#        run: |
#
#          : set PATH=%cd%\swoole-cli-v5.0.3-cygwin-x64\bin\;%PATH%
#
#          : swoole-cli.exe /cygdrive/d/a/swoole-cli/swoole-cli/swoole-cli-v5.0.3-cygwin-x64/bin/composer.phar config -g repos.packagist composer https://packagist.org
#          : swoole-cli.exe /cygdrive/d/a/swoole-cli/swoole-cli/swoole-cli-v5.0.3-cygwin-x64/bin/composer.phar update --prefer-dist -vvv --profile --no-dev
#          : swoole-cli.exe /cygdrive/d/a/swoole-cli/swoole-cli/swoole-cli-v5.0.3-cygwin-x64/bin/composer.phar update --prefer-source  -vvv --profile --no-dev
#
#          : swoole-cli.exe prepare.php --without-docker=1 --skip-download=1
#
#          : 本命令无效 ，只是为了看输出
#          call php-sdk-binary-tools\phpsdk-vs16-x64.bat

#      - name: "Install PHP for official runners"
#        uses: "shivammathur/setup-php@v2"
#        with:
#          coverage: none
#          tools: composer:v2
#          php-version: 8.2
#          ini-values: memory_limit=-1
#
      - name: Set PHPSDK  Github ENV variables
        run: |
          echo "PHP_SDK_ARCH=x64" >> $Env:GITHUB_ENV
          echo "PHP_SDK_BIN_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin" >> $Env:GITHUB_ENV
          echo "PHP_SDK_MSYS2_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\msys2\usr\bin" >> $Env:GITHUB_ENV
          echo "PHP_SDK_OS_ARCH=x64" >> $Env:GITHUB_ENV
          echo "PHP_SDK_PHP_CMD=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin\php\do_php.bat" >> $Env:GITHUB_ENV
          echo "PHP_SDK_ROOT_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools" >> $Env:GITHUB_ENV
          echo "PHP_SDK_VC_DIR=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC" >> $Env:GITHUB_ENV
          echo "PHP_SDK_VC_TOOLSET_VER=$env:VCToolsVersion" >> $Env:GITHUB_ENV
          echo "PHP_SDK_VS=vs17" >> $Env:GITHUB_ENV
          echo "PHP_SDK_VS_NUM=17" >> $Env:GITHUB_ENV
          echo "PHP_SDK_VS_SHELL_CMD=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64" >> $Env:GITHUB_ENV

          $CURRENT_DIR = Get-Location
          $X_PATH="${CURRENT_DIR}\php-sdk-binary-tools\bin;${CURRENT_DIR}\php-sdk-binary-tools\msys2\usr\bin;$env:PATH"
          echo $X_PATH
          echo "PATH=$X_PATH"  >> $Env:GITHUB_ENV

      - name: build all library
        shell: cmd
        run: |
          echo %cd%
          set __PROJECT__=%cd%
          set "PATH=%PATH%;%__PROJECT__%\php\;%__PROJECT__%\nasm\"
          perl -v
          nasm -v

          cmd /c  sapi\quickstart\windows\native\zlib.bat
          cmd /c  sapi\quickstart\windows\native\openssl.bat

      - name: build php
        run: |
          $CURRENT_DIR = Get-Location

          # cmd /c sapi\quickstart\windows\native-build\native-build-php-sdk-vs2019.bat

          cmd /c sapi\quickstart\windows\native-build\native-build-php-config.bat

          cmd /c sapi\quickstart\windows\native-build\native-build-php-config-help.bat

          cmd /c sapi\quickstart\windows\native-build\native-build-php-build.bat

          cmd /c sapi\quickstart\windows\native-build\native-build-php-build-release.bat

          cmd /c sapi\quickstart\windows\native-build\native-build-php-build-archive.bat


      - name: test set env in cmd
        if: 0
        shell: cmd
        run: |
          ： 脚本所在目录
          echo %cd%
          SET  CURRENT_DIR=%cd%

          : set PATH=%cd%\swoole-cli-v5.0.3-cygwin-x64\bin\;%PATH%
          : swoole-cli.exe -v

          set PHP_SDK_ARCH=x64
          set PHP_SDK_BIN_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin
          set PHP_SDK_MSYS2_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\msys2\usr\bin
          set PHP_SDK_OS_ARCH=x64
          set PHP_SDK_PHP_CMD=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin\php\do_php.bat
          set PHP_SDK_ROOT_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools
          set "PHP_SDK_VC_DIR=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC"
          set "PHP_SDK_VC_TOOLSET_VER=%VCToolsVersion%"
          set PHP_SDK_VS=vs16
          set PHP_SDK_VS_NUM=16
          set "PHP_SDK_VS_SHELL_CMD=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
          set PATH=%cd%\php\;%PATH%
          set "PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin;D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\msys2\usr\bin;%PATH%"
          echo %PATH%

          cd %CURRENT_DIR%
          echo %cd%

          cd php-src
          call buildconf
          call configure --help
          call configure --disable-all  --disable-cgi --enable-cli --enable-sockets  --enable-mbstring  --enable-ctype  --enable-pdo --enable-phar  --enable-xmlreader  --enable-xmlwriter --enable-zlib
          call nmake
          D:\a\swoole-cli\swoole-cli\php-src\x64\Release_TS\php.exe -v
          D:\a\swoole-cli\swoole-cli\php-src\x64\Release_TS\php.exe -m




