name: build-php-cli-windows-2019

on:
  push:
  pull_request:

env:
  BUILD_PHP_VERSION: 8.2.13

jobs:
  windows-native:
    if: 1
    runs-on: windows-2019
    strategy:
      matrix:
        php-version:
        #  - "8.2.13"
        #  - "8.1.27"
          - "8.3.7"

    steps:
      - uses: actions/checkout@v4
      - name: show environment info
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all
          echo "BUILD_PHP_VERSION=${{ matrix.php-version }}" >> $Env:GITHUB_ENV

      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            curl git unzip tar xz

      - uses: actions/setup-dotnet@v1
      - uses: ilammy/msvc-dev-cmd@v1.9.0
        with:
          arch: amd64

      - uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          packages: git curl wget zip unzip tar xz

      - name: download cygwin php runtime
        shell: msys2 {0}
        # shell: C:\cygwin\bin\bash.exe  --norc -eo pipefail -o igncr '{0}'
        run: |
          bash setup-php-runtime.sh
          pwd
          export PATH=$(pwd)/swoole-cli-v5.0.3-cygwin-x64/bin:$PATH
          swoole-cli -v

      - name: prepare source code
        shell: cmd
        run: |
          git clone -b master --depth=1 https://github.com/php/php-sdk-binary-tools.git
          git clone -b php-${{ env.BUILD_PHP_VERSION }} --depth=1 https://github.com/php/php-src.git
          : 本命令无效 ，只是为了看输出
          call php-sdk-binary-tools\phpsdk-vs16-x64.bat

      - name: test
        shell: cmd
        run: |
          echo %~dp0
          echo %cd%
          SET  CURRENT_DIR=%~dp0
          set PATH=%cd%\swoole-cli-v5.0.3-cygwin-x64\bin\;%PATH%
          echo %PATH%
          swoole-cli.exe -v
          set PHP_SDK_ARCH=x64
          set PHP_SDK_BIN_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin
          set PHP_SDK_MSYS2_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\msys2\usr\bin
          set PHP_SDK_OS_ARCH=x64
          set PHP_SDK_PHP_CMD=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin\php\do_php.bat
          set PHP_SDK_ROOT_PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools
          set "PHP_SDK_VC_DIR=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC"
          set "PHP_SDK_VC_TOOLSET_VER=%VCToolsVersion%"
          set PHP_SDK_VS=vs16
          set PHP_SDK_VS_NUM=16
          set "PHP_SDK_VS_SHELL_CMD=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
          set "PATH=D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\bin;D:\a\swoole-cli\swoole-cli\php-sdk-binary-tools\msys2\usr\bin;%PATH%"

          set
          cd php-src
          call buildconf
          call configure --help
          call configure --disable-all --enable-cli --enable-static=yes --enable-shared=no
          call nmake
          D:\a\swoole-cli\swoole-cli\php-src\x64\Release_TS\php.exe -v
          D:\a\swoole-cli\swoole-cli\php-src\x64\Release_TS\php.exe -m

